version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    container_name: siem-elasticsearch-final
    environment:
      - cluster.name=siem-cluster-final
      - node.name=siem-node-final
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
      - action.destructive_requires_name=false
      # Disk watermark settings for low disk space
      - cluster.routing.allocation.disk.watermark.low=98%
      - cluster.routing.allocation.disk.watermark.high=99%
      - cluster.routing.allocation.disk.watermark.flood_stage=99.5%
      # Additional optimizations
      - indices.memory.index_buffer_size=20%
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - siem-network
    volumes:
      - es-data-final:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.15
    container_name: siem-kibana-final
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_HOST: "0.0.0.0"
      XPACK_SECURITY_ENABLED: "false"
      XPACK_ML_ENABLED: "false"
      XPACK_GRAPH_ENABLED: "false"
      XPACK_WATCHER_ENABLED: "false"
      XPACK_MONITORING_ENABLED: "false"
      # Optimize for low resources
      NODE_OPTIONS: "--max-old-space-size=512"
      # Allow yellow cluster status
      ELASTICSEARCH_REQUESTTIMEOUT: 60000
      ELASTICSEARCH_PINGTIMEOUT: 30000
      LOGGING_ROOT_LEVEL: warn
    ports:
      - "5601:5601"
    networks:
      - siem-network
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.15
    container_name: siem-logstash-final
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./configs/logstash/pipeline:/usr/share/logstash/pipeline
      - ./configs/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
    networks:
      - siem-network
    depends_on:
      elasticsearch:
        condition: service_healthy

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.15
    container_name: siem-filebeat-final
    user: root
    volumes:
      - ./configs/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log:/var/log:ro
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/syslog:/var/log/syslog:ro
      - /var/log/kern.log:/var/log/kern.log:ro
    command: filebeat -e -strict.perms=false
    networks:
      - siem-network
    depends_on:
      - logstash

networks:
  siem-network:
    driver: bridge

volumes:
  es-data-final:
    driver: local