services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: siem-elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=siem-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
      - ./configs/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - siem-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: siem-logstash
    volumes:
      - ./configs/logstash/pipeline:/usr/share/logstash/pipeline
      - ./configs/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logs/sample-data:/usr/share/logstash/sample-data
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - siem-network
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: siem-kibana
    volumes:
      - ./configs/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - siem-network
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: siem-filebeat
    user: root
    volumes:
      - ./configs/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs/sample-data:/usr/share/filebeat/sample-data:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
    command: filebeat -e -strict.perms=false
    networks:
      - siem-network
    depends_on:
      - logstash

  elastalert:
    image: jertel/elastalert2:latest
    container_name: siem-elastalert
    volumes:
      - ./alerting/elastalert.yml:/opt/elastalert/config.yaml:ro
      - ./alerting/rules:/opt/elastalert/rules:ro
    networks:
      - siem-network
    depends_on:
      - elasticsearch

networks:
  siem-network:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
