http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
pipeline.workers: 2
pipeline.batch.size: 1000
pipeline.batch.delay: 50
config.reload.automatic: true
config.reload.interval: 3s
dead_letter_queue.enable: true
