cluster.name: siem-cluster
node.name: siem-node-1

# Path settings
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery settings for single node
discovery.type: single-node

# Memory settings
bootstrap.memory_lock: true

# Security settings (disabled for development)
xpack.security.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# Monitoring
xpack.monitoring.collection.enabled: true

# Index settings optimized for security logs
action.auto_create_index: +siem-*,+security-*,+firewall-*,+auth-*,-*

# Performance tuning for SIEM workloads
indices.memory.index_buffer_size: 20%
indices.queries.cache.size: 20%
indices.fielddata.cache.size: 40%

# Index lifecycle management
xpack.ilm.enabled: true

# Index templates for time-series data
index.number_of_shards: 1
index.number_of_replicas: 0
index.refresh_interval: 30s
